### PR TITLE
Reformatted python files

### PR DESCRIPTION
**Pull request by BMaster123**
The python files are reformatted to follow the guidelines in PEP 8 in order to make them readable.

### CODE REVIEW

**Comment by PremApk** [comment]
First Make sure you get recent files before coding.

**Comment by PremApk** [comment]
Just give "git pull upstream main". Just make sure you add this main repository as upstream

**Comment by Twiggecode** [comment]
This pull request has many merge conflicts, they're conflicting with some of the more recent pull requests.

This isn't something I've encountered before and I'm not sure of the best way to deal with this, could you possibly create a new pull request using the updated repository? Thanks.

**Comment by BMaster123** [comment]
I'm not sure why this happened either but all I had to do was enter "git pull upstream main" like @PremApk said and accept incoming changes to all the files that had merge conflict and reformat them.

**Pull request merged**
