### PR TITLE
Primes

### PR DESCRIPTION
**Pull request by itsf4llofstars**
Cleaned some formatting errors, correct some spelling errors.
Corrected functions for loop as it was return true for 51, 1003, 1271883 all of which are non prime numbers.

### CODE REVIEW

**Comment by itsf4llofstars** [comment]
Hi, thanks for this repo, it really helps. I'm new to github so learning. Please let me know if I need to do something different. I also have a new faster .cpp primes file, do I need to wait for this pull req. to clear or close before I can do a pull req. on the new file? I'm not seeing a pull req. over on my fork after I pushed from my computer.  Again thanks so much.
Cheers

**Comment by Sedatyf** [comment]
Hi @itsf4llofstars and welcome. Don't worry, everyone started somewhere. What you can right now you can edit your first message, and use the Pull request template in the repository. Then, you'll have to wait the maintainer to merge your pull request. If you want to do other edits on other files, you can do a new branch in your fork and then do a new pull request. Let me know if I wasn't clear enough

**Comment by Twiggecode** [comment]
@itsf4llofstars I'm merging this pull request now, so you can submit a new pull request for your faster .cpp primes file.

**Comment by itsf4llofstars** [comment]
Thank you all. Somehow I the prime .cpp file that I wrote got included in the pull request for the .cpp file I corrected spelling errors on. I'm not sure how I ended up doing that. I'm not to much worried as long as I didn't do any to mess up an easy work flow for you all. Thanks for all your help, I like learning new things and this repository makes watching and learning github. These next pull req. I'm going to do one at a time on an algorithm so I can more easily sit back and watch how the process moves along. Thanks. 
Cheers

**Pull request merged**
