### PR TITLE
Update TrackingProgress.md

### PR DESCRIPTION
**Pull request by Ash-KODES**
Removing c++ from fibonacci series checklist since it is already done by me 
thankyou

### CODE REVIEW

**Comment by YaadR** [comment]
The checklist follows what languages have already been added. 
No need to delete the C++ if the code exists.

**Comment by Ash-KODES** [comment]
> The checklist follows what languages have already been added.
> No need to delete the C++ if the code exists.

so how can i update the TrackingProgress.md file as per the pull request template?

**Comment by YaadR** [comment]
You can Update the Tracking List for example after you've added a new code implementation or if you just see that it's not up to date with the progress of the project.

As for the Pull Request Template there is a different file by this name. You can find it under "Pull Request Template.md"
This is different issue, where you can suggest something like a checklist that will appear automatically as part of the pull request action in order to smooth the process.
You can find an example and more details in the issue post.

Take a second to read the README file and I'm sure it will be clear.

**Comment by Twiggecode** [comment]
Yes as YaadR has said, the languages added on the tracking list are the languages in which code already exists. So we will never remove languages from there, only add more.

The pull request template is a work in progress to simplify the process of submitting a pull request.

**Comment by Ash-KODES** [comment]
ok thanks for clarification

**Pull request closed without merging**
