### PR TITLE
Created pell_numbers.java

### PR DESCRIPTION
**Pull request by BMaster123**

### CODE REVIEW

**Comment by PremApk** [comment]
I think it exists already!

**Comment by PremApk** [comment]
@BMaster123 You did any modifications? I don't find any!

**Comment by BMaster123** [comment]
My bad. For some reason, I can't see the java version in vs code. Do I have to periodically fork the repository to see any new additions? I think I forked the repository before pell_numbers.java was added.

**Comment by PremApk** [comment]
No just use git pull command to update your repository before coding

**Comment by BMaster123** [comment]
Ok thank you

**Pull request closed without merging**
